#!/bin/sh -l

# Part of tiny-radioCD project, originally designed & hand-crafted by macmpi
# check License at project home https://github.com/macmpi/tiny-radioCD


# if PLAY/PAUSE is followed by same, below a max DELAY then SWITCH_SPKR
CUR="$(awk '{print $1}' /proc/uptime)"

# init for first push and no STAMP
OLD="$CUR"
TEST="0"


exec 4<> /tmp/.STAMP    # Processes semaphore with time stamp
flock -x 4

[ -s /tmp/.STAMP ] && OLD="$(cat /tmp/.STAMP)"

# Set time STAMP reference to trigger quick transitions follow-up
printf "$CUR" > /tmp/.STAMP

flock -u 4
exec 4<&-


. GLOBALS # needs full path so sh-l in shebang!
[ "$CUR" != "$OLD" ] && TEST="$( echo "$CUR - $OLD < $G_DELAY" | bc )"

[ "$TEST" -eq "1" ] && /etc/acpi/remote/SWITCH_SPKR
mpc toggle > /dev/null 2>&1



