#!/bin/sh -l

# Part of tiny-radioCD project, originally designed & hand-crafted by macmpi
# check License at project home https://github.com/macmpi/tiny-radioCD


# if PLAY/PAUSE is followed by PREVIOUS below a max DELAY then POWEROFF
CUR="$(awk '{print $1}' /proc/uptime)"

# init for first push and no STAMP
PLAY="$CUR"
TEST="0"

[ -s /tmp/.STAMP ] && PLAY="$(cat /tmp/.STAMP)"

. GLOBALS # needs full path so sh-l in shebang!
[ "$CUR" != "$PLAY" ] && TEST="$( echo "$CUR - $PLAY < $G_DELAY_KEYS" | bc )"

if [ "$TEST" -eq "1" ]; then
	/etc/acpi/remote/POWEROFF
else
	mpc -q prev
fi

