#!/bin/sh -l

# Part of tiny-radioCD project, originally designed & hand-crafted by macmpi
# check License at project home https://github.com/macmpi/tiny-radioCD


# does not make sense for Radios as infinite tracks
grep -q "RADIO" /tmp/.SOURCE || mpc -q random on

