#!/bin/sh -l

# Part of tiny-radioCD project, originally designed & hand-crafted by macmpi
# check License at project home https://github.com/macmpi/tiny-radioCD


# toggle repeat mode on/off
mpc -q repeat

