#!/bin/sh

# Part of tiny-radioCD project, originally designed & hand-crafted by macmpi
# check License at project home https://github.com/macmpi/tiny-radioCD


# creates a new user with username, group and pass provided as input
USERNAME="$1"
GROUP="$2"
PASS="$3"

export SEXPECT_SOCKFILE=/tmp/SOCKFILE
sexpect spawn -autowait adduser -h /tmp -G $GROUP $USERNAME

sexpect expect -exact "New password:" > /dev/null 2>&1
sexpect send -enter "$PASS" > /dev/null 2>&1

sexpect expect -exact "Retype password:" > /dev/null 2>&1
sexpect send -enter "$PASS" > /dev/null 2>&1

sexpect expect -exact "changed by root" > /dev/null 2>&1

