#!/bin/sh

# Part of tiny-radioCD project, originally designed & hand-crafted by macmpi
# check License at project home https://github.com/macmpi/tiny-radioCD


# Makes an image & remove sshd; optionally locks-out root

! [ $(id -u) -eq 0 ] && { echo >&2 "Please run as root (i.e. with sudo)"; exit 1; }


########## Install tiny-radioCD
chmod +x install
./install


########## do some clean-up
echo "tiny-radiocd" > /etc/hostname
hostname -F /etc/hostname

rc-update del sshd default
apk del openssh

rc-update del dropbear default
apk del dropbear

# clear ssh keys on image: will be recreated on first sshd start
rm -f /etc/ssh/ssh_host_*
rm -f /etc/dropbear/dropbear_*_host_key


########## Manage accounts: root & eventual admin
# Optionally lock-out root and no admin if non-empty parameter
if [ -z "$1" ]; then

	# create admin:wheel user with tiny-radioCD pass
	chmod +x create-user
	./create-user admin wheel tiny-radioCD   # homedir /tmp

	# allow doas for wheel group
	grep -q "permit persist :wheel" /etc/doas.d/doas.conf || \
	echo "permit persist :wheel" >> /etc/doas.d/doas.conf


	# enable dropbear ssh
	apk add dropbear
	rc-update add dropbear default
	grep -q "root=" /proc/cmdline || touch /etc/tiny-radiocd_ssh_nokeys

	passwd -d root  # expiring it would require shadow package

else

    mv /etc/securetty /etc/securetty.orig
    touch /etc/securetty
    chmod 600 /etc/securetty

    sed -i '/:0:0:/s_/bin/ash_/sbin/nologin_' /etc/passwd

    passwd -l root

fi

cat <<-EOF > /etc/network/interfaces
	auto lo
	iface lo inet loopback

	EOF

rm -f /etc/wpa_supplicant/wpa_supplicant.conf
rm -f /etc/resolv.conf
rm -rf /var/lib/bluetooth/*

grep -q "root=" /proc/cmdline || lbu commit -d

