#!/bin/sh

# Part of tiny-radioCD project, originally designed & hand-crafted by macmpi
# check License at project home https://github.com/macmpi/tiny-radioCD


# Note: this file is included so all upper variables work
# do NOT change directory inside here, or cd "$srcdir" at the end!...


# Limited Pi-specific customizations regarding swclock & configs

echo "Installing Pi specific tweaks"

# on Pi no hardware clock
service hwclock stop 2>&1
rc-update del hwclock boot 2>&1
service swclock start 2>&1
rc-update add swclock boot 2>&1


#################################
# Modify usercfg.txt content for boot options
Pi_PATH="$( find /media -type d -path '*/.*' -prune -o -type f -name config.txt -exec dirname {} \; | head -1 )"
mount -o remount,rw "$Pi_PATH"

# Pi eventual supplements for config.txt or usrcfg.txt

# eventual gpu_mem MUST be set in original config.txt, not in include
# https://github.com/raspberrypi/firmware/issues/1332#issuecomment-584166999
# gpu_mem=16 to reduce memory footprint (requires _cd files to be installed)

# Disable the rainbow splash screen (will not add if there and commented)
grep -q "disable_splash=1" "$Pi_PATH"/usercfg.txt || \
echo "disable_splash=1" >> "$Pi_PATH"/usercfg.txt

# Set the bootloader delay to 0 seconds. Default is 1s if not specified.
# (will not add if there and commented)
grep -q "boot_delay=0" "$Pi_PATH"/usercfg.txt || \
echo "boot_delay=0" >> "$Pi_PATH"/usercfg.txt

# Bluetooth enabled by kernel/overlays by default (post kernel 6.1.25)
# due to missing HW flowcontrol on Pi3b rev1.2 boards
# one may want to limit baudrate with dtparam=krnbt_baudrate=<rate here>

# built-in audio, and HDMI audio (will not add if there and commented)
grep -q "dtparam=audio=on" "$Pi_PATH"/usercfg.txt || \
echo "dtparam=audio=on" >> "$Pi_PATH"/usercfg.txt

# set HDMI safe (will not add if there and commented)
# https://www.raspberrypi.com/documentation/computers/config_txt.html#hdmi-mode
grep -q "hdmi_safe=1" "$Pi_PATH"/usercfg.txt || \
echo "hdmi_safe=1" >> "$Pi_PATH"/usercfg.txt

# set HDMI boost to max (will not add if there and commented)
grep -q "config_hdmi_boost" "$Pi_PATH"/usercfg.txt || \
echo "config_hdmi_boost=7" >> "$Pi_PATH"/usercfg.txt

# ON/OFF button on GPIO3
#dtoverlay=gpio-shutdown

# External activity LED on GPIO 21
#dtparam=act_led_gpio=21

mount -o remount,ro "$Pi_PATH"


#################################
# Preserve local specific stuff according to install modes

if !(grep -q "root=" /proc/cmdline); then  #we are not in sys mode (so data or diskless)
	# stuff of matter for diskless or data mode
		
	if !(grep -q "/var" /etc/fstab); then #we are not in data mode: hence diskless only
		# stuff from /var for diskless mode
		:
	fi
fi


echo "Done with Pi specific tweaks"
