#!/bin/sh

# Part of tiny-radioCD project, originally designed & hand-crafted by macmpi
# check License at project home https://github.com/macmpi/tiny-radioCD


# Note: this file is included so all upper variables work
# do NOT change directory inside here, or cd "$srcdir" at the end!...


# Limited x86-specific customizations

echo "Installing x86 specific tweaks"

# adding nomodeset to boot option in grub.cfg & syslinux.cfg
# some old NVIDIA GPUs have driver issues that collide once eudev is set
# https://gitlab.alpinelinux.org/alpine/aports/-/issues/14010
x86_FILE="$(find /boot /media -type d -path '*/.*' -prune -o -type f -name grub.cfg 2>/dev/null | head -1)"
if ! grep -q nomodeset "$x86_FILE"; then
	echo "Setting nomodeset boot option in grub & syslinux.cfg"
	x86_MOUNTPOINT="$(df "$x86_FILE" | awk '{ print $6 }' | tail -1)"
	! touch "$x86_FILE" > /dev/null 2>&1; RO=$?
	[ $RO -eq "0" ] && mount -o remount,rw "$x86_MOUNTPOINT"
	sed -i 's/ quiet/ nomodeset quiet/' "$x86_FILE"
	sed -i 's/ quiet/ nomodeset quiet/' "${x86_FILE%/*/*}/syslinux/syslinux.cfg"
	sync
	[ $RO -eq "0" ] && mount -o remount,ro "$x86_MOUNTPOINT"
fi

echo "*** WARNING!! Machine may not boot if missing GPU firmware ***"
# NOTE: in addition some GPU card firmware drivers may be necessary.
# For instance for older Macs (i.e nvidia 9400M) linux-firmware-nvidia must
# be installed in addition (not part of default firmware modloop).
# As /lib/firmware is not writeable on diskless/data modes, a ext4
# persistent storage needs to be added and overlayed
# (other partition or persist .img file), hence /etc/fstab adjusted accordingly
# i.e. https://wiki.alpinelinux.org/wiki/Raspberry_Pi#Persistent_stotage


#################################
# Preserve local specific stuff according to install modes

if !(grep -q "root=" /proc/cmdline); then  #we are not in sys mode (so data or diskless)
	# stuff of matter for diskless or data mode
		
	if !(grep -q "/var" /etc/fstab); then #we are not in data mode: hence diskless only
		# stuff from /var for diskless mode
		:
	fi
fi


echo "Done with x86 specific tweaks"
